"""add_compliance_check_export_log_notification

Revision ID: 4906a5094a60
Revises: fb69956d07c5
Create Date: 2026-04-11 18:35:03.084070
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4906a5094a60'
down_revision: Union[str, None] = 'fb69956d07c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notifications_unread', 'notifications', ['user_id'], unique=False, postgresql_where='read = false')
    op.create_index('idx_notifications_user_id', 'notifications', ['user_id'], unique=False)
    op.create_table('compliance_checks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('artifact_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_compliance_checks_artifact_id', 'compliance_checks', ['artifact_id'], unique=False)
    op.create_table('export_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('artifact_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('format', sa.String(length=50), nullable=False),
    sa.Column('compliance_score', sa.Float(), nullable=True),
    sa.Column('exported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_export_logs_artifact_id', 'export_logs', ['artifact_id'], unique=False)
    op.create_index('idx_export_logs_user_id', 'export_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_export_logs_user_id', table_name='export_logs')
    op.drop_index('idx_export_logs_artifact_id', table_name='export_logs')
    op.drop_table('export_logs')
    op.drop_index('idx_compliance_checks_artifact_id', table_name='compliance_checks')
    op.drop_table('compliance_checks')
    op.drop_index('idx_notifications_user_id', table_name='notifications')
    op.drop_index('idx_notifications_unread', table_name='notifications', postgresql_where='read = false')
    op.drop_table('notifications')
    # ### end Alembic commands ###
