"""initial_schema

Revision ID: fb69956d07c5
Revises: 
Create Date: 2026-04-11 16:24:17.056399
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb69956d07c5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_documents',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('document_type', sa.Enum('MAS_REGULATION', 'PRODUCT_FACT_SHEET', 'DISCLAIMER', name='document_type'), nullable=False),
    sa.Column('chunk_index', sa.Integer(), server_default='0', nullable=False),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_compliance_documents_source', 'compliance_documents', ['source_document_id'], unique=False)
    op.create_index('idx_compliance_documents_type', 'compliance_documents', ['document_type'], unique=False)
    op.create_table('users',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('BRAND_ADMIN', 'DISTRICT_LEADER', 'AGENCY_LEADER', 'FSC', name='user_role'), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('agent_id', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_users_agent_id', 'users', ['agent_id'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_table('brand_kit',
    sa.Column('name', sa.String(length=255), server_default='Default', nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('secondary_logo_url', sa.String(length=500), nullable=True),
    sa.Column('primary_color', sa.String(length=7), server_default='#D0103A', nullable=False),
    sa.Column('secondary_color', sa.String(length=7), server_default='#1A1A18', nullable=False),
    sa.Column('accent_color', sa.String(length=7), server_default='#1B9D74', nullable=False),
    sa.Column('fonts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_brand_kit_updated_by', 'brand_kit', ['updated_by'], unique=False)
    op.create_table('compliance_rules',
    sa.Column('rule_text', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.Enum('ERROR', 'WARNING', name='compliance_severity'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_compliance_rules_active', 'compliance_rules', ['id'], unique=False, postgresql_where='is_active = true')
    op.create_index('idx_compliance_rules_category', 'compliance_rules', ['category'], unique=False)
    op.create_index('idx_compliance_rules_created_by', 'compliance_rules', ['created_by'], unique=False)
    op.create_table('projects',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('PERSONAL', 'TEAM', name='project_type'), nullable=False),
    sa.Column('purpose', sa.Enum('PRODUCT_LAUNCH', 'CAMPAIGN', 'SEASONAL', 'AGENT_ENABLEMENT', name='project_purpose'), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('product', sa.String(length=255), nullable=True),
    sa.Column('target_audience', sa.String(length=500), nullable=True),
    sa.Column('campaign_period', sa.String(length=255), nullable=True),
    sa.Column('key_message', sa.Text(), nullable=True),
    sa.Column('brand_kit_id', sa.UUID(), nullable=True),
    sa.Column('brief', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='active', nullable=False),
    sa.Column('deleted_at', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_kit_id'], ['brand_kit.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_projects_brand_kit_id', 'projects', ['brand_kit_id'], unique=False)
    op.create_index('idx_projects_owner_id', 'projects', ['owner_id'], unique=False)
    op.create_index('idx_projects_type', 'projects', ['type'], unique=False)
    op.create_table('artifact_suggestions',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('artifact_type', sa.Enum('POSTER', 'WHATSAPP_CARD', 'REEL', 'STORY', 'VIDEO', 'DECK', 'INFOGRAPHIC', 'SLIDE_DECK', name='artifact_type'), nullable=False),
    sa.Column('artifact_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('audience', sa.Enum('INTERNAL', 'EXTERNAL', 'BOTH', name='suggestion_audience'), nullable=False),
    sa.Column('selected', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_artifact_suggestions_project_id', 'artifact_suggestions', ['project_id'], unique=False)
    op.create_table('artifacts',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('POSTER', 'WHATSAPP_CARD', 'REEL', 'STORY', 'VIDEO', 'DECK', 'INFOGRAPHIC', 'SLIDE_DECK', name='artifact_type'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('channel', sa.Enum('INSTAGRAM', 'WHATSAPP', 'PRINT', 'SOCIAL', 'INTERNAL', name='artifact_channel'), nullable=True),
    sa.Column('format', sa.Enum('SQUARE', 'PORTRAIT_4_5', 'PORTRAIT_9_16', 'A4', 'WA_SQUARE', name='artifact_format'), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('compliance_score', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'READY', 'EXPORTED', name='artifact_status'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('deleted_at', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('compliance_score IS NULL OR (compliance_score >= 0 AND compliance_score <= 100)', name='ck_artifacts_compliance_score_range'),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_artifacts_creator_id', 'artifacts', ['creator_id'], unique=False)
    op.create_index('idx_artifacts_project_id', 'artifacts', ['project_id'], unique=False)
    op.create_index('idx_artifacts_status', 'artifacts', ['status'], unique=False)
    op.create_index('idx_artifacts_type', 'artifacts', ['type'], unique=False)
    op.create_table('project_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'MEMBER', name='project_member_role'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_project_member')
    )
    op.create_index('idx_project_members_project_id', 'project_members', ['project_id'], unique=False)
    op.create_index('idx_project_members_user_id', 'project_members', ['user_id'], unique=False)
    op.create_table('brand_library_items',
    sa.Column('artifact_id', sa.UUID(), nullable=False),
    sa.Column('published_by', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_REVIEW', 'APPROVED', 'PUBLISHED', 'REJECTED', name='library_item_status'), nullable=False),
    sa.Column('remix_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['published_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_brand_library_items_artifact_id', 'brand_library_items', ['artifact_id'], unique=False)
    op.create_index('idx_brand_library_items_published_by', 'brand_library_items', ['published_by'], unique=False)
    op.create_index('idx_brand_library_items_status', 'brand_library_items', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_brand_library_items_status', table_name='brand_library_items')
    op.drop_index('idx_brand_library_items_published_by', table_name='brand_library_items')
    op.drop_index('idx_brand_library_items_artifact_id', table_name='brand_library_items')
    op.drop_table('brand_library_items')
    op.drop_index('idx_project_members_user_id', table_name='project_members')
    op.drop_index('idx_project_members_project_id', table_name='project_members')
    op.drop_table('project_members')
    op.drop_index('idx_artifacts_type', table_name='artifacts')
    op.drop_index('idx_artifacts_status', table_name='artifacts')
    op.drop_index('idx_artifacts_project_id', table_name='artifacts')
    op.drop_index('idx_artifacts_creator_id', table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index('idx_artifact_suggestions_project_id', table_name='artifact_suggestions')
    op.drop_table('artifact_suggestions')
    op.drop_index('idx_projects_type', table_name='projects')
    op.drop_index('idx_projects_owner_id', table_name='projects')
    op.drop_index('idx_projects_brand_kit_id', table_name='projects')
    op.drop_table('projects')
    op.drop_index('idx_compliance_rules_created_by', table_name='compliance_rules')
    op.drop_index('idx_compliance_rules_category', table_name='compliance_rules')
    op.drop_index('idx_compliance_rules_active', table_name='compliance_rules', postgresql_where='is_active = true')
    op.drop_table('compliance_rules')
    op.drop_index('idx_brand_kit_updated_by', table_name='brand_kit')
    op.drop_table('brand_kit')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_agent_id', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_compliance_documents_type', table_name='compliance_documents')
    op.drop_index('idx_compliance_documents_source', table_name='compliance_documents')
    op.drop_table('compliance_documents')
    # ### end Alembic commands ###
