"use client";

import Box from "@mui/material/Box";
import Typography from "@mui/material/Typography";
import { LogoCard } from "../logo-card";
import type { BrandKit } from "@/types/brand-kit";

interface LogoVaultTabProps {
  kit: BrandKit;
  isAdmin: boolean;
  onLogoUpload: (file: File, variant: "primary" | "secondary") => Promise<void>;
}

const COMPOSITING_RULES = [
  "Logo is never generated by AI — always composited from this vault",
  "Clear space is enforced programmatically — no text/imagery enters padding ring",
  "Primary logo used when poster has ≥180px width in logo zone",
  "Secondary icon mark used for WhatsApp cards and narrow zones",
  "SVG format ensures pixel-perfect rendering at any export resolution",
];

export function LogoVaultTab({ kit, isAdmin, onLogoUpload }: LogoVaultTabProps) {
  return (
    <Box
      sx={{
        display: "grid",
        gridTemplateColumns: { xs: "1fr", md: "1fr 1fr 1fr" },
        gap: 2.5,
      }}
    >
      <LogoCard
        label="Primary logo"
        subLabel="Full lockup — used on posters, video title cards"
        currentUrl={kit.logo_url}
        specs="Min width 120px · Clear space 16px · Format: SVG"
        isAdmin={isAdmin}
        onUpload={(file) => onLogoUpload(file, "primary")}
      />
      <LogoCard
        label="Secondary logo"
        subLabel="Icon mark only — used on WhatsApp cards, small formats"
        currentUrl={kit.secondary_logo_url}
        specs="Min width 40px · Clear space 8px · Format: SVG"
        isAdmin={isAdmin}
        onUpload={(file) => onLogoUpload(file, "secondary")}
      />
      <Box
        sx={{
          border: "1px solid #E8EAED",
          borderRadius: "12px",
          p: 2.5,
          backgroundColor: "#F7F7F7",
        }}
      >
        <Typography sx={{ fontSize: 14, fontWeight: 600, mb: 1.5 }}>
          Compositing rules
        </Typography>
        {COMPOSITING_RULES.map((rule, i) => (
          <Box key={i} sx={{ display: "flex", gap: 1, mb: 1.25 }}>
            <Typography sx={{ fontSize: 12, color: "#5F6368", lineHeight: 1.1, flexShrink: 0 }}>
              {i + 1}.
            </Typography>
            <Typography sx={{ fontSize: 12, color: "#5F6368", lineHeight: 1.5 }}>
              {rule}
            </Typography>
          </Box>
        ))}
      </Box>
    </Box>
  );
}
